### ISSUE TITLE
New features

### ISSUE THREAD

**Issue by milesj** [michael-donat/php-vfs#19]
Hey again, so I'm currently converting https://github.com/titon/io tests to use this library, and these are some features that are missing. I'm not sure what is possible with streams or not, so just let me know what is and isn't possible.
- symlinks (is_link(), lchgrp(), lchown(), etc)
- is_executable()

I've also noticed some weirdness with `rename()` in regards to folders. Specifically, this test: https://github.com/titon/io/blob/master/tests/Titon/Io/NodeTest.php#L201 According to the docs, rename should overwrite the target, so I'm assuming that the folder contents get moved to the new location. I'm not 100% positive how folder renaming works in PHP land, so will need to test more before I submit an issue.

**Comment by michael-donat** [comment]
Renaming directories on top of existing includes the renamed into existing, have a look here

```
donatm@osx-donatm:/tmp$ cd milesj/
donatm@osx-donatm:/tmp/milesj$ mkdir source
donatm@osx-donatm:/tmp/milesj$ mkdir -p target/contents
donatm@osx-donatm:/tmp/milesj$ ll source/
total 0
drwxr-xr-x  2 donatm  wheel   68 30 Apr 07:59 .
drwxr-xr-x  4 donatm  wheel  136 30 Apr 07:59 ..
donatm@osx-donatm:/tmp/milesj$ ll target/
total 0
drwxr-xr-x  3 donatm  wheel  102 30 Apr 07:59 .
drwxr-xr-x  4 donatm  wheel  136 30 Apr 07:59 ..
drwxr-xr-x  2 donatm  wheel   68 30 Apr 07:59 contents
donatm@osx-donatm:/tmp/milesj$ mv target source
donatm@osx-donatm:/tmp/milesj$ ll
total 0
drwxr-xr-x   3 donatm  wheel  102 30 Apr 07:59 .
drwxrwxrwt  20 root    wheel  680 30 Apr 07:59 ..
drwxr-xr-x   3 donatm  wheel  102 30 Apr 07:59 source
donatm@osx-donatm:/tmp/milesj$ ll source/
total 0
drwxr-xr-x  3 donatm  wheel  102 30 Apr 07:59 .
drwxr-xr-x  3 donatm  wheel  102 30 Apr 07:59 ..
drwxr-xr-x  3 donatm  wheel  102 30 Apr 07:59 target
donatm@osx-donatm:/tmp/milesj$
```

`mv target source` moved target into source, not replaced. This is the behaviour I recreated.

**Comment by michael-donat** [comment]
Digging further,

```
<?php
        mkdir('/tmp/a');
        mkdir('/tmp/b');

        rename('/tmp/a', '/tmp/b');
```

Above removed a and replaced with b.

While

```
<?php
        mkdir('/tmp/aa', 0777, true);
        mkdir('/tmp/bb', 0777, true);
        file_put_contents('/tmp/bb/file', 'data');

        rename('/tmp/aa', '/tmp/bb');
```

Resulted in `rename(/tmp/aa,/tmp/bb): Directory not empty`

This is probably the behaviour to be expected. I will adjust as soon as I have some time.

**Comment by michael-donat** [comment]
I'm also looking at Links. This is possible, need to add another Node type that's all.

**Comment by milesj** [comment]
Awesome, thanks for looking into it. I'll implement more of the more complex areas next to see if there's anything else missing.

**Comment by milesj** [comment]
Found another one: `flock`

**Comment by michael-donat** [comment]
@milesj what's wrong with is_executable? Seems to be working fine with a simple true/false case?

**Comment by milesj** [comment]
During this test, it would always fail. https://github.com/titon/io/blob/master/tests/Titon/Io/NodeTest.php#L247

Didn't look into it much though.

**Comment by michael-donat** [comment]
``` bash
/usr/local/Cellar/php55/5.5.11/bin/php /private/var/folders/y1/hclnhr051gl3lyrvx9vz5qs40000gn/T/ide-phpunit.php --configuration /Volumes/Development/io/phpunit.xml.dist --filter "/::testPermissionReading( .*)?$/" Titon\Io\NodeTest /Volumes/Development/io/tests/Titon/Io/NodeTest.php
Testing started at 19:43 ...
PHPUnit 4.0.7 by Sebastian Bergmann.

Configuration read from /Volumes/Development/io/phpunit.xml.dist



Time: 59 ms, Memory: 4.50Mb

OK (1 test, 8 assertions)

Process finished with exit code 0
```

**Comment by michael-donat** [comment]
Right, against DIR it will always return false. PHP limitation.

**Comment by milesj** [comment]
Derp, I knew it was something simple. Thanks for looking, always nice to have another set of eyes.

**Comment by michael-donat** [comment]
Have moved everything else to separate issues. Will close this.
