### ISSUE TITLE
Force user to root?

### ISSUE THREAD

**Issue by milesj** [michael-donat/php-vfs#30]
I'm trying to unit test the `chown` and `chgrp` functions, but it fails with a permission denied since the user running the tests isn't root. Is there a way in the library to force the user in VFS to root? So that functionality can be tested?

Tests in question: https://travis-ci.org/titon/io/jobs/25759945

**Comment by michael-donat** [comment]
The chgrp is quite clear - fixed to not require root.

As far as chown goes, all my tests between ubuntu/osx tell me that ownership change is not allowed unless you are root.

**Comment by milesj** [comment]
Guess I can just skip those tests if the user != 0.

**Comment by michael-donat** [comment]
I will allow chmod if user == owner, it makes sense that way.
