### ISSUE TITLE
Should DIRECTORY_SEPARATOR be used?

### ISSUE THREAD

**Issue by tim-bezhashvyly** [michael-donat/php-vfs#36]
While writing a test should `DIRECTORY_SEPARATOR` constant be used or `/` will always work? This is a virtual file system of course but if run on a Windows based system will it still use forward or backward slashes?

**Comment by michael-donat** [comment]
This Filesystem uses / for separator. No need to support for windows separator.

**Comment by tim-bezhashvyly** [comment]
Thanks for clarification.
