### ISSUE TITLE
scandir() is not returning current and parent directories

### ISSUE THREAD

**Issue by tim-bezhashvyly** [michael-donat/php-vfs#37]
If you do `scandir` against a directory it is supposed that first two elements of an array would be `.` and `..`.

**Comment by michael-donat** [comment]
Is this behaviour also expected on Windows? I wonder whether the fact that `.` and `..` are returned is something specific to unix file systems.

Quick fix may be to create a stubbed structure that has 2 directories in it

Below hasn't been tested, just an idea.

```
\VirtualFileSystem\FileSystem::createStructure(['.'=>[], '..'=>[]])
```

Anyway, I'm all for adding this in if we can prove that this is the behaviour regardless of the platform, if not, then the consideration will be on whether we should try to mimic unix fs here or not.

**Comment by tim-bezhashvyly** [comment]
Sorry, have no access to Windows with PHP. You have to test it by yourself :stuck_out_tongue:

I checked `scandir` description on php.net and there's nothing about difference in behaviour on Windows systems.

Thank you for the workaround.
