### ISSUE TITLE
PHP 7.1 failing tests

### ISSUE THREAD

**Issue by twifty** [michael-donat/php-vfs#46]
Is the project being maintained? I see it hasn't been updated in 2 years.

I have just tried using the vfs within a test case, without success.
```php
        $fs = new FileSystem();
        
        $fs->createStructure([
            'var' >= [
                'www' >= [
                    'package.json' => '{}',
                    'project' => [
                        'vendor' => [],
                    ],
                ],
            ],
        ]);
        
        $this->assertTrue(file_exists($fs->path('/var/www/package.json')), "Filesystem failed!");
```
I can see from the projects own test cases, the above code should work without a problem. So, I'm guessing it's the PHP version I'm using (PHP 7.1.5-1+deb.sury.org~xenial+2).

It's a shame since this is the only virtual system which "should" support symlinks.

**Comment by michael-donat** [comment]
What was it buddy? ;)

**Comment by twifty** [comment]
Damn I need new glasses. `>=` caused the array to become [0 => true].
