### ISSUE TITLE
Support for fileinfo extenstion

### ISSUE THREAD

**Issue by glynnforrest** [michael-donat/php-vfs#51]
Thank you for the time you've spent on this project so far.

It doesn't look like the fileinfo extension works correctly. Do you think it would be possible to add this functionality?

Failing code:

```php
$vfs = new \VirtualFileSystem\FileSystem();
$vfs->createFile('/file.txt', 'Hello world');
$finfo = new \Finfo(FILEINFO_MIME);
echo $finfo->file($vfs->path('/file.txt'));
```

**Comment by michael-donat** [comment]
@glynnforrest I think that might be it, can you please test the branch and let know if this is what you had in mind?

**Comment by glynnforrest** [comment]
@michael-donat wow, that was quick! I've just tested the `finfo` branch and can confirm it works correctly.

Thanks very much!

**Comment by michael-donat** [comment]
no worries, I will clean up and release tomorrow, prolly as 1.4.0 with php-7.2 requirement

**Comment by glynnforrest** [comment]
Excellent, although it'd be great if you could support php 7.0 (for Debian Stretch).

**Comment by michael-donat** [comment]
tagged as https://github.com/michael-donat/php-vfs/releases/tag/v1.4.0 with php >= 7.0 support
